apiVersion: v1
kind: ReplicationController
metadata:
  name: $SERVICE_NAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: $SERVICE_NAME
    spec:
      containers:
      - name: echoserver
        image: k8s.gcr.io/echoserver:1.4
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
